---
title: "Assignment 5: Revisiting your code (part 1)"
---

Now that you've had some practice with `R` and the format of the course, it's time to pause and take a moment to check in on what you've learned. Because we haven't had a ton of coding yet, this review is a little more conceptual (rather than focusing on particular pieces you may have done incorrectly or inefficiently). My soluionts (or suggestions) for how I'd approach the first four assignments are posted (at the end of each assignment page). Your task here is to review those solutions and your own code and answer a few questions to demonstrate what you've learned so far and where I need to be more clear. You'll still be using Quarto to complete [this homework](https://classroom.github.com/a/niVSeHuF). 

## Instructions

1. After you've joined the assignment repository, you should have this file (named Readme.md) inside of a R project named assignment-revision-1-xx where xx is your github username (or initials).

2. Once you've verified that you've correctly cloned the assignment repository, create a new Quarto document. Name this file ar1_xxx.qmd and give it a title (like M Williamson Assignment Revision 1). Make sure that you select the html output option (Quarto can do a lot of cool things, but the html format is the least-likely to cause you additional headaches). We'll be using Quarto throughout the course so it's worth checking out the other tutorials in the getting started section.

3. Copy the questions [in the assignment](https://classroom.github.com/a/niVSeHuF) into your document and change the color of their text.

4. Save the changes and make your first commit!

5. Answer the questions making sure save and commit at least 4 more times (having 3 commits is part of the assignment).

6. Render the document (by clicking the "Render" button in RStudio) to html (you should now have at least 3 files in the repository: Readme.md, ar1_xx.qmd, and ar1_xx.html). Commit these changes and push them to the repository on GitHub. You should see the files there when you go to github.com.

## Questions

1. How do you introduce yourself to git? (look at some of the initial lectures for the course) How often do you need to introduce yourself when you are on the RStudio server? What is the difference between a "commit" and a "push"?

2. How do you check the Coordinate Reference System of a vector file using the `sf` package? What about for a raster file using the `terra` package? Why is the CRS important?

3.  What is the difference between a predicate and a measure?

4. As you look back on your first few assignments, what has been the biggest challenge? Do you feel like you know how to solve it? How can I help?

5. As you look back on the first few weeks of lectures, what is the _one_ thing that you wish I would do differently (I'll do my best!)

6. Tell me about your final project - what topic are you hoping to explore? What data are going to use? (Remember, this assignment works better if you're using data that isn't part of your thesis) If there are things I can do to help you find data or a topic, please let me know here.
