---
title: "Assignment Revision 2: Revisiting your code"
---

This is your second opportunity to reconsider your answers to the previous two assignments and evaluate what you might have done differently now that you've had a little more practice. Solutions (or suggestions) for how I'd approach past assignments are posted (at the end of each assignment page). Your task here is to review those solutions and your own code and answer a few questions to demonstrate what you've learned so far and where I need to be more clear. I've also asked some specific questions based on common challenges across the assignments. You'll still be using Quarto to complete [this homework](https://classroom.github.com/a/k2kHDvLA). 

## Instructions

1. After you've joined the assignment repository, you should have this file (named Readme.md) inside of a R project named assignment-revision-2-xx where xx is your github username (or initials).

2. Once you've verified that you've correctly cloned the assignment repository, create a new Quarto document. Name this file ar2_xxx.qmd and give it a title (like M Williamson Assignment Revision 1). Make sure that you select the html output option (Quarto can do a lot of cool things, but the html format is the least-likely to cause you additional headaches). We'll be using Quarto throughout the course so it's worth checking out the other tutorials in the getting started section.

3. Copy the questions in the assignment into your document and change the color of their text.

4. Save the changes and make your first commit!

5. Answer the questions making sure save and commit at least 2 more times (having 3 commits is part of the assignment).

6. Render the document (by clicking the "Render" button in RStudio) to html (you should now have at least 3 files in the repository: Readme.md, ar1_xx.qmd, and ar1_xx.html). Commit these changes and push them to the repository on GitHub. You should see the files there when you go to github.com.

## Questions

1. Imagine you have a spatial analysis planned that uses one tabular dataset, 2 vector datasets, and 2 raster datasets. What are the basic steps that you need to do before you can build a spatial database from all the data sources in R? You can write the steps in pseudocode, bullet point, or paragraph form.

2. What are your strategies for checking that an operation resulted in the output you expected? In general, how do you identify and correct syntax errors and semantic errors (see [session 6](https://isdrfall24.classes.spaseslab.com/content/06-content.html) for definitions) in your work? If you don't, what strategies would you like to try going forward?

3. Compare your assignments 6-7 with the posted solutions. Were you able to answer all the questions? If not, correct and notate your code and push the changes to GitHub.

4. As you look back on assignments 6-7, what has been the biggest challenge? Do you feel like you know how to solve it? How can I help?

5. As you look back on the past few weeks of lectures, what is the _one_ thing you appreciate and _one_ thing that you wish I would do differently? (I'll do my best!)

6. Tell me about your final project - how have your plans progressed since the last time you checked in with me?