---
title: "Final Self-reflection"
---

This is the [last self-reflection](https://classroom.github.com/a/2T785OPE) for the semester. It is intended to be an opportunity to reflect on your progress in the course relative to your goals, to identify places where you'd like to dig deeper, and to highlight parts of the class that worked or didn't work for you.  **This final reflection is the ultimate assessment of your performance in the course.** As such, I'm asking that you complete this in a timely fashion and turn it in by **Dec. 13**.

## Instructions

1. After you've joined the assignment repository, you should have this file (named `Readme.md`) inside of a R project named `self-reflection-final-xx` where `xx` is your github username (or initials). 

2. Once you've verified that you've correctly cloned the assignment repository, [create a new Quarto document](https://quarto.org/docs/get-started/authoring/rstudio.html). Name this file `self-reflection-final-xxx.qmd` and give it a title (like M Williamson Final Self-Reflection). Make sure that you select the `html` output option (Quarto can do a lot of cool things, but the html format is the least-likely to cause you additional headaches). We'll be using Quarto throughout the course so it's worth checking out the other tutorials in the getting started section.

3. Copy the questions below into your document and [change the color of their text](https://meghan.rbind.io/blog/quarto-slides/).

4. Save the changes and make your first commit!

5. Render the document to html (you should now have at least 3 files in the repository: Readme.md, self-reflection-final-xx.qmd, and self-reflection-final-xx.html). Commit these changes and push them to the repository on GitHub. You should see the files there when you go to github.com.

## Questions

**About you**

1. Look back at your goals for this course. How would you say you did? Did you get as far as you'd hoped? Can you point to examples in your final project that serve as examples of you meeting your goals?

2. Did you have goals that you didn't meet? What got in your way?

3. Which parts of this course are you likely to use in your research?

4. Thinking about your research, what is one topic you wished we had covered in this course?

**This Course**

5. What did you like the best about this course?

6. What did you like the least about this course?

7. What is one topic you wish we had spent more time on in class?

8. What is one topic you wish we had spent less time on in class?

9. Did the homework assignments help you cement the concepts we covered in class? If not, why not?

**Final Thoughts**

10. Is there anything else you'd like me to know about you or that you want to know about the course?